[tasks.format]
command = "npx"
args = ["prettier", "--write", "**/*.md"]

[tasks.watch]
command = "mdbook"
args = ["watch", "--open"]
dependencies = ["install-mdbook"]

[tasks.build]
command = "mdbook"
args = ["build"]
dependencies = ["install-mdbook"]

[tasks.clean]
command = "mdbook"
args = ["clean"]
dependencies = ["install-mdbook"]

[tasks.install-mdbook]
install_crate = { crate_name = "mdbook", binary = "mdbook", test_arg = "--help" }
run_task = "install-mdbook-mermaid"

[tasks.install-mdbook-mermaid]
install_crate = { crate_name = "mdbook-mermaid", binary = "mdbook-mermaid", test_arg = "--help" }
