name: Build Book
on:
  push:
    branches:
      - main
jobs:
  publish_book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: cargo-cache

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
